### ISSUE TITLE
Add additional maintainers please

### ISSUE THREAD

**Issue by joshka** [sagebind/stability#12]
Hi Stephen,

We use stability in [Ratatui](https://github.com/ratatui-org/ratatui) to mark items unstable until we're ready to more widely commit to a specific API.

I notice that you're a bit too busy to handle PRs in this repo. That's obviously totally fine and I mean to cast no shade on your choice / lack of availability.

I'd like to propose adding another maintainer or two (myself and perhaps @orhun if he's interested) that can merge PRs and perform releases. I'm happy to contribute workflows that make this as simple as merging a PR generated by release-plz. (See https://github.com/joshka/tui-popup/pull/15 for an example).

Alternatively if you're not comfortable with adding more maintainers, I'd like to fork of this crate so that we can release it more rapidly.

**Comment by sagebind** [comment]
Hey Josh, thanks for asking! I've had a heavy workload for the past year which limits my flexibility to work on open-source stuff. However, I like to tell myself that my projects are just pretty sleepy and not dead. 😀

At this time, I'm not currently willing to accept more maintainers, but that could change in the future. Feel free to ask again later to see if I ever change my mind...

So here's what I can say and recommend:

- Not this week, but coming up around the 16th I should have a timeslot where I can do some open source maintenance tasks, and will try my best to address pending PRs and do a release for this project (among others).
- However, this does not address the core of your need to release rapidly, which a one-time effort from me will not solve. If you need more rapid releases than I can deliver, go ahead and make a fork of this project for your uses so that you can make changes whenever you need, I wouldn't take any offense at all. I will, however, keep maintaining this repo (as sporadic as it might be).

How does that sound?

**Comment by joshka** [comment]
Sounds good to me. If you have a chance, there's just that one PR about re-exports which should be just a few minutes to review.

**Comment by joshka** [comment]
I've forked this to https://github.com/ratatui-org/instability
