### ISSUE TITLE
The `unstable` feature badge for items

### ISSUE THREAD

**Issue by loyd** [sagebind/stability#4]
It would be nice to add a badge `unstable` for items with `#[stability::unstable]`:
![2022-01-15_11-19-05](https://user-images.githubusercontent.com/952180/149615000-af9134c5-9310-4726-8756-be0c02f75857.png)

A common approach for this (e.g. used by `tokio`) is relying on the `doc_cfg` feature. [Details](https://stackoverflow.com/questions/61417452/how-to-get-a-feature-requirement-tag-in-the-documentation-generated-by-cargo-do). It works fine with the current docsrs.

So, `#[stability::unstable]` can additionally generate `#[cfg_attr(docsrs, doc(cfg(feature = "unstable")))]`. However, it still requires `#![cfg_attr(docsrs, feature(doc_cfg))]` at crate level and
```toml
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
```
in Cargo.toml

The good news is that it doesn't fail even if these steps haven't added.

Will you accept the PR with an additional feature (`docsrs-cfg`?) that enables generation of `#[cfg_attr(docsrs, doc(cfg(feature = "unstable")))]`?

**Comment by sagebind** [comment]
I'm not sure adding the additional feature is worth the complexity, especially since you can use the `doc_auto_cfg` nightly feature to have `doc(cfg)` applied everywhere there is a `cfg` gated item. I use this in some of my crates to get the cfg badges:

```rust
#![cfg_attr(feature = "nightly", feature(doc_cfg))]
#![cfg_attr(feature = "nightly", feature(doc_auto_cfg))]
```

Then I enable the `nightly` feature in Cargo.toml like so:

```toml
[package.metadata.docs.rs]
features = ["nightly"]
```

There's probably other ways of doing this as well without needing to modify the `stability` macros.

**Comment by loyd** [comment]
`doc_auto_cfg` is much better than modifying `stability`. Thanks a lot)
